-- Create the table for storing scraped articles
CREATE TABLE IF NOT EXISTS scraped_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT UNIQUE NOT NULL,
    title TEXT,
    content TEXT,
    scraped_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    source_domain TEXT,
    status TEXT DEFAULT 'active'
);

-- Enable Row Level Security (RLS) - Optional/Recommended
ALTER TABLE scraped_articles ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow read/write access (Adjust based on your auth needs)
-- For a simple internal tool using the Service Key, this might not be strictly necessary if RLS is off, 
-- but good practice to allow the service role full access.
CREATE POLICY "Allow service role full access" ON scraped_articles
    FOR ALL
    USING (true)
    WITH CHECK (true);
